"""Pack the Unity project's FBX models into web/models.js so index.html works from file:// and as a single hosted page.

Run from the repo root:  python3 web/build-models.py
"""
import base64, io, os
from PIL import Image

SRC = os.path.join(os.path.dirname(__file__), "..", "TopDownRPG", "Assets", "Sprites")
MATS = os.path.join(os.path.dirname(__file__), "..", "TopDownRPG", "Assets", "Materials")
# Albedo maps the cottage, tavern and room FBX files point at, shrunk to 256px JPEGs.
TEXTURES = ["Plaster1", "WoodFlooring", "WoodTexture.1", "glass", "grassroof", "riverstonebrick.lowpoly", "roof.1"]
MODELS = ["character.pieces_R", "cottage", "tavern", "mottecastle", "Room1fbx", "tree", "tree_ash"]

out = ["// Generated by build-models.py from TopDownRPG/Assets/Sprites/*.fbx. Do not edit by hand.",
       "window.TRAPPIST_FBX = {"]
for name in MODELS:
    with open(os.path.join(SRC, name + ".fbx"), "rb") as f:
        out.append('  "%s": "%s",' % (name, base64.b64encode(f.read()).decode()))
out.append("};")
out.append("window.TRAPPIST_TEX = {")
for name in TEXTURES:
    im = Image.open(os.path.join(MATS, name + "_albedo.png")).convert("RGB").resize((256, 256), Image.LANCZOS)
    buf = io.BytesIO(); im.save(buf, "JPEG", quality=82)
    out.append('  "%s_albedo.png": "data:image/jpeg;base64,%s",' % (name, base64.b64encode(buf.getvalue()).decode()))
out.append("};")
with open(os.path.join(os.path.dirname(__file__), "models.js"), "w") as f:
    f.write("\n".join(out) + "\n")
print("wrote models.js")
