"""Pack the Unity project's FBX models into web/models.js so index.html works from file:// and as a single hosted page.

Run from the repo root:  python3 web/build-models.py
"""
import base64, os

SRC = os.path.join(os.path.dirname(__file__), "..", "TopDownRPG", "Assets", "Sprites")
MODELS = ["character.pieces_R", "cottage", "tavern", "mottecastle", "Room1fbx", "tree", "tree_ash"]

out = ["// Generated by build-models.py from TopDownRPG/Assets/Sprites/*.fbx. Do not edit by hand.",
       "window.TRAPPIST_FBX = {"]
for name in MODELS:
    with open(os.path.join(SRC, name + ".fbx"), "rb") as f:
        out.append('  "%s": "%s",' % (name, base64.b64encode(f.read()).decode()))
out.append("};")
with open(os.path.join(os.path.dirname(__file__), "models.js"), "w") as f:
    f.write("\n".join(out) + "\n")
print("wrote models.js")
